---
title: "Covid.19"
output:
  github_document:
    fig_width: 9
    fig_height: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```

O intuito deste repositório é colaborar, do ponto de vista estatístico e computacional, com as pesquisas que estão sendo desenvolvidades sobre o novo corona vírus (COVID-19). Neste primeiro momento, estou recolhendo informações e deixando aqui no README todas as referências que eu encontrei emitidas por orgãos governamentais, ONG's e ferramentas que estão sendo desenvolvidas.

Qualquer tipo de contribuição será muito bem vinda! Pode ser novas referências, correção de texto, implementação de novas funções, etc. Quem puder contribuir de alguma forma pode me contactar no email samuelmacedo@recife.ifpe.edu.br ou deixar seus comentário na [issues](https://github.com/samuelmacedo83/covid.19/issues) aqui no github.


Estas são as referências:

* JSON com os dados https://api.coronaanalytic.com/brazil
* Código em python https://github.com/belisards/coronabr
* Crawler com os relatorios em PDF https://github.com/javierluraschi/covid
* pacote em R com dados organizados https://github.com/RamiKrispin/coronavirus
* plataforma.saude.gov.br http://plataforma.saude.gov.br/novocoronavirus/
* John Hopkins github https://github.com/CSSEGISandData/COVID-19
* mapa COVID-19 https://systems.jhu.edu/research/public-health/ncov/
* kaggle datasets https://www.kaggle.com/sudalairajkumar/novel-corona-virus-2019-dataset
* World Health Organization (WHO): https://www.who.int/ 
* DXY.cn. Pneumonia. 2020. http://3g.dxy.cn/newh5/view/pneumonia. 
* BNO News: https://bnonews.com/index.php/2020/02/the-latest-coronavirus-cases/ 
* National Health Commission of the People’s Republic of China (NHC): http&#58;://www.nhc.gov.cn/xcs/yqtb/list_gzbd.shtml
* China CDC (CCDC): http&#58;://weekly.chinacdc.cn/news/TrackingtheEpidemic.htm 
* Hong Kong Department of Health: https://www.chp.gov.hk/en/features/102465.html
* Macau Government: https://www.ssm.gov.mo/portal/
* Taiwan CDC: https://sites.google.com/cdc.gov.tw/2019ncov/taiwan?authuser=0
* US CDC: https://www.cdc.gov/coronavirus/2019-ncov/index.html
* Government of Canada:
https://www.canada.ca/en/public-health/services/diseases/coronavirus.html
* Australia Government Department of Health: https://www.health.gov.au/news/coronavirus-update-at-a-glance
* European Centre for Disease Prevention and Control (ECDC): https://www.ecdc.europa.eu/en/geographical-distribution-2019-ncov-cases

